[project]
name = "bundles-and-packages-manager-and-quoter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "lxml>=6.0.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "st-gsheets-connection>=0.1.0",
    "xlsxwriter>=3.2.9",
]
